### ISSUE TITLE
7.1.1 Fatal error

### ISSUE THREAD

**Issue by MichelVen** [Tribler/tribler.github.com#47]
7.1.1. fails to execute script run_tribler

**Comment by xoriole** [comment]
Thank you for reporting. It seems the issue is because of failed configuration upgrade of the proxy settings.
Please try removing following fields from configuration file `triblerd.conf` located at your state directory.
>proxy_server = “”
>proxy_auth = “”

The new proxy configuration will be autocreated next time you run tribler. 

Also, please re-open this issue on our main Tribler repository: https://github.com/tribler/tribler if above fix does not work. This is the repository that hosts only our website.
